# Generated by Django 4.0.4 on 2022-06-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'namaz',
                'ordering': ['code'],
            },
        ),
    ]
